config/routes.rb
Rails.application.routes.draw do
  resources :survey_answers
  resources :survey_questions
  resources :survey_responses do
    member do
      get 'download_pdf', :defaults => { :format => 'pdf' }
      get 'send_pdf_document'
    end
  end
  resources :questions
  resources :question_categories
  resources :surveys
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "question_categories#index"
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :survey_questions, dependent: :destroy
  has_many :survey_responses
  has_many :users, through: :survey_responses
	after_create :set_code_name

	def set_code_name
		code_name = "DOC" + ("%05d" % id).to_s
        self.update_attribute(:code_name, code_name.upcase)
	end

	def create_survey_details(questions, user, sub_code)
		questions.each do |question|
		  survey_question = SurveyQuestion.new
		  survey_question.question = question
		  survey_question.survey = self
		  survey_question.save
		end
		
		survey_response = SurveyResponse.new
		survey_response.user = user
		survey_response.survey = self
		survey_response.status = false
		survey_response.code_name = self.code_name + "-" + ("%03d" % sub_code).to_s.upcase
		survey_response.save
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]
  before_action :get_question_categories, only: %i[ new create edit ]

  # GET /surveys or /surveys.json
  def index
    #@surveys = Survey.all

  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    users = User.where(id: params[:user_ids])
    questions = Question.where(id: params[:questions])
    respond_to do |format|
      if users.present? && questions.present?
          survey = Survey.new
        users.each_with_index do |user, idx|
          Survey.transaction do
            survey.save
            survey.create_survey_details(questions, user, idx+1)
          end
        end
        format.html { redirect_to survey_url(survey), notice: "QuestionSet was successfully created." }
        format.json { render :new, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    def get_question_categories
      @question_categories = QuestionCategory.where('question_categories.active = ? and questions.active = ?', true, true).joins(:questions).select('name', 'body', 'questions.id').group_by(&:name)
      @users = User.where(admin: false).pluck(:email, :id)
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:code_name)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_tag surveys_path, id: "survey_form" do %>

<%count = 0%>
<%@question_categories.each do |category, questions|%>
  <%count += 1%>
<div class="cls_cat_question">
  <input type="checkbox" /><b><%= count%>. <%= category%></b>
</div>
<div>
  <ul class="cls_question">
    <%questions.each_with_index do |question, idx|%>
    <li>
      <%= check_box_tag 'questions[]', question.id, false, class: "cls_chk_questions" %><%= count%>.<%= idx+1%>
      <%= question.body%>
    </li>
    <%end%>
  </ul>
</div>
<%end%>
<div>
  <%= select_tag 'user_ids', options_for_select(@users),{class: "form-control",  multiple: true, required: true, size: "5x1"} %>
</div>
<div><br><%= submit_tag 'Save',class: "btn btn-primary" %>  <%#= link_to "Back", new_survey_path %></div>
<%end%>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
  <p>
    <strong>Code name:</strong>
    <%= survey.code_name %>
  </p>

</div>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render "form", survey: @survey %>

<br>

<div>
  <%= link_to "Show this survey", @survey %> |
  <%= link_to "Back", new_survey_path %>
</div>

app/views/surveys/index.html.erb
<%= link_to "New survey", new_survey_path %>

app/views/surveys/new.html.erb
<h1>New QuestionSet</h1>

<%= render "form", survey: @survey %>

app/views/surveys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survey %>

<div>
  <%= link_to "Edit", edit_survey_path(@survey) %> |
  <%= link_to "Back", new_survey_path %>

  <%#= button_to "Delete", @survey, method: :delete, class: "btn btn-danger" %>
</div>