config/routes.rb
Rails.application.routes.draw do
  resources :survey_answers
  resources :survey_questions
  resources :survey_responses do
    member do
      get 'download_pdf', :defaults => { :format => 'pdf' }
      get 'send_pdf_document'
    end
  end
  resources :questions
  resources :question_categories
  resources :surveys
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "question_categories#index"
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
	has_many :questions
	acts_as_paranoid
end

app/controllers/question_categories_controller.rb
class QuestionCategoriesController < ApplicationController
  before_action :set_question_category, only: %i[ show edit update destroy ]

  # GET /question_categories or /question_categories.json
  def index
    @question_categories = QuestionCategory.all
  end

  # GET /question_categories/1 or /question_categories/1.json
  def show
  end

  # GET /question_categories/new
  def new
    @question_category = QuestionCategory.new
  end

  # GET /question_categories/1/edit
  def edit
  end

  # POST /question_categories or /question_categories.json
  def create
    @question_category = QuestionCategory.new(question_category_params)

    respond_to do |format|
      if @question_category.save
        format.html { redirect_to question_categories_url, notice: "Question category was successfully created." }
        format.json { render :show, status: :created, location: @question_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_categories/1 or /question_categories/1.json
  def update
    respond_to do |format|
      if @question_category.update(question_category_params)
        format.html { redirect_to question_category_url(@question_category), notice: "Question category was successfully updated." }
        format.json { render :show, status: :ok, location: @question_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_categories/1 or /question_categories/1.json
  def destroy
    @question_category.destroy

    respond_to do |format|
      format.html { redirect_to question_categories_url, notice: "Question category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_category
      @question_category = QuestionCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_category_params
      params.require(:question_category).permit(:name, :active)
    end
end

app/helpers/question_categories_helper.rb
module QuestionCategoriesHelper
end

app/views/question_categories/_form.html.erb
<%= form_with(model: question_category) do |form| %>
  <% if question_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question_category.errors.count, "error") %> prohibited this question_category from being saved:</h2>

      <ul>
        <% question_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-2">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name,  class: 'form-control' %>
  </div>

  <div class="col-md-1">
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :active, class: 'form-control' %>
  </div>

  <div class="col-md-1">
    <br><%= form.submit 'Save',class: "btn btn-primary" %>
  </div>
<% end %>

app/views/question_categories/_question_category.html.erb
<tr>
  <td><%= question_category.name %></td>
  <td><%= question_category.active ? 'Active' : 'Inactive' %></td>
  <td><%= link_to question_category_path(question_category), method: :delete do %>
    <span class="glyphicon glyphicon-remove"></span> Remove 
    <%end%>
  </td>
</tr>

app/views/question_categories/edit.html.erb
<h1>Editing question category</h1>

<%= render "form", question_category: @question_category %>

<br>

<div>
  <%= link_to "Show this question category", @question_category %> |
  <%= link_to "Back to question categories", question_categories_path %>
</div>

app/views/question_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h2>Question categories</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @question_categories.each do |question_category| %>
        <%= render question_category %>
      <%end%>
    </tbody>
  </table>
</div>

<%= link_to "New question category", new_question_category_path %>

app/views/question_categories/new.html.erb
<h1>New question category</h1>

<%= render "form", question_category: @question_category %>



<div class="row">
  <br><%= link_to "Back", question_categories_path %>
</div>

app/views/question_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question_category %>

<div>
  <%= link_to "Edit this question category", edit_question_category_path(@question_category) %> |
  <%= link_to "Back to question categories", question_categories_path %>

  <%= button_to "Destroy this question category", @question_category, method: :delete %>
</div>