config/routes.rb
Rails.application.routes.draw do
  resources :survey_answers
  resources :survey_questions
  resources :survey_responses do
    member do
      get 'download_pdf', :defaults => { :format => 'pdf' }
      get 'send_pdf_document'
    end
  end
  resources :questions
  resources :question_categories
  resources :surveys
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "question_categories#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionnaireApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%#= javascript_importmap_tags %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">DemoApp</a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <%= link_to destroy_user_session_path, method: :delete  do%>
            <span class="glyphicon glyphicon-user"></span> Logout
          <%end%>
        </li>
        <%else%>
        <li>
          <%= link_to new_user_session_path  do%>
          <span class="glyphicon glyphicon-log-in"></span> Login
          <%end%>
        </li>
        <%end%>
      </ul>
    </div>
  </nav>

  <style>
    
  </style>
</head>

<body>

 <% if user_signed_in? %>
  <div class="sidebar">
    <%if current_user.admin?%>
      <a href="<%= question_categories_path%>">Categories</a>
      <a href="<%= questions_path%>">Questions</a>
      <a href="<%= new_survey_path%>">New QuestionSet</a>
      <a href="<%= survey_responses_path%>">All QuestionSets</a>
    <%else%>
      <a href="<%= survey_responses_path%>" class="active">QuestionSets</a>
    <%end%>
  </div>

  <!-- Page content -->
  <div class="content">
    <%= yield %>    
  </div>
  <%else%>
    <%= yield %>
  <%end%>

</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  
<title>PDFs</title>
</head>
<body>
    <%= yield %>
</body>
</html>